# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.13.0
#   kernelspec:
#     display_name: nlpbook
#     language: python
#     name: nlpbook
# ---

# %%
from argparse import Namespace

import nltk
import numpy as np
import pandas as pd
from nltk.tokenize import word_tokenize

# %%
args = Namespace(
    source_data_path="data/nmt/eng-fra.txt",
    output_data_path="data/nmt/simplest_eng_fra.csv",
    perc_train=0.7,
    perc_val=0.15,
    perc_test=0.15,
    seed=1337,
)

assert args.perc_test > 0 and (
    args.perc_test + args.perc_val + args.perc_train == 1.0
)

# %%
with open(args.source_data_path) as fp:
    lines = fp.readlines()

lines = [line.replace("\n", "").lower().split("\t") for line in lines]

# %%
import os

nltk_data_path = os.path.abspath("../../../nltk_data/")
tokenizer = nltk.data.load(nltk_data_path + "/tokenizers/punkt/english.pickle")
nltk.data.path.append(nltk_data_path)
# %%
data = []
for english_sentence, french_sentence in lines:
    data.append(
        {
            "english_tokens": word_tokenize(
                english_sentence, language="english"
            ),
            "french_tokens": word_tokenize(french_sentence, language="french"),
        }
    )

# %%
filter_phrases = (
    ("i", "am"),
    ("i", "'m"),
    ("he", "is"),
    ("he", "'s"),
    ("she", "is"),
    ("she", "'s"),
    ("you", "are"),
    ("you", "'re"),
    ("we", "are"),
    ("we", "'re"),
    ("they", "are"),
    ("they", "'re"),
)


# %%
data_subset = {phrase: [] for phrase in filter_phrases}
for datum in data:
    key = tuple(datum["english_tokens"][:2])
    if key in data_subset:
        data_subset[key].append(datum)

# %%
# data_subset will look like
# ```python
# (('they', "'re"),
#  [{'english_tokens': ['they', "'re", 'bad', '.'],
#    'french_tokens': ['ils', 'sont', 'mauvais', '.']},
#   {'english_tokens': ['they', "'re", 'bad', '.'],
#    'french_tokens': ['elles', 'sont', 'mauvaises', '.']},
#   {'english_tokens': ['they', "'re", 'old', '.'],
#    'french_tokens': ['ils', 'sont', 'vieux', '.']},
#   {'english_tokens': ['they', "'re", 'old', '.'],
#    'french_tokens': ['elles', 'sont', 'vieilles', '.']},
#   {'english_tokens': ['they', "'re", 'back', '.'],
#    'french_tokens': ['ils', 'sont', 'de', 'retour', '.']},
#   {'english_tokens': ['they', "'re", 'back', '.'],
#    'french_tokens': ['elles', 'sont', 'de', 'retour', '.']},
#   {'english_tokens': ['they', "'re", 'boys', '.'],
#    'french_tokens': ['ce', 'sont', 'des', 'garçons', '.']},
#   {'english_tokens': ['they', "'re", 'cold', '.'],
#    'french_tokens': ['ils', 'sont', 'froids', '.']},
#   {'english_tokens': ['they', "'re", 'cold', '.'],
#    'french_tokens': ['elles', 'sont', 'froides', '.']},
#   {'english_tokens': ['they', "'re", 'cool', '.'],
#    'french_tokens': ['ils', 'sont', 'sympa', '.']},
#   {'english_tokens': ['they', "'re", 'cool', '.'],
#    'french_tokens': ['elles', 'sont', 'sympa', '.']},
#   {'english_tokens': ['they', "'re", 'cops', '.'],
#    'french_tokens': ['ce', 'sont', 'des', 'flics', '.']},
#   {'english_tokens': ['they', "'re", 'cute', '.'],
#    'french_tokens': ['ils', 'sont', 'mignons', '.']},
#   {'english_tokens': ['they', "'re", 'cute', '.'],
#    'french_tokens': ['elles', 'sont', 'mignonnes', '.']},
#   {'english_tokens': ['they', "'re", 'dead', '.'],
#    'french_tokens': ['ils', 'sont', 'décédés', '.']},
#   {'english_tokens': ['they', "'re", 'dead', '.'],
#    'french_tokens': ['elles', 'sont', 'décédées', '.']},
#   {'english_tokens': ['they', "'re", 'done', '.'],
#    'french_tokens': ['ils', 'ont', 'terminé', '.']},
#   {'english_tokens': ['they', "'re", 'done', '.'],
#    'french_tokens': ['elles', 'ont', 'terminé', '.']},
#   {'english_tokens': ['they', "'re", 'free', '.'],
#    'french_tokens': ['ils', 'sont', 'libres', '.']},
#   {'english_tokens': ['they', "'re", 'free', '.'],
#    'french_tokens': ['elles', 'sont', 'libres', '.']},
#   {'english_tokens': ['they', "'re", 'gone', '.'],
#    'french_tokens': ['ils', 'sont', 'partis', '.']},
#   {'english_tokens': ['they', "'re", 'gone', '.'],
#    'french_tokens': ['elles', 'sont', 'parties', '.']},
#   {'english_tokens': ['they', "'re", 'gone', '.'],
#    'french_tokens': ['il', 'n', "'", 'y', 'en', 'a', 'plus', '.']},
#   {'english_tokens': ['they', "'re", 'here', '.'],
#    'french_tokens': ['ils', 'sont', 'là', '.']},
#   {'english_tokens': ['they', "'re", 'mine', '.'],
#    'french_tokens': ['ils', 'sont', 'à', 'moi', '.']},
#   {'english_tokens': ['they', "'re", 'mine', '.'],
#    'french_tokens': ['ils', 'sont', 'miens', '.']},
#   {'english_tokens': ['they', "'re", 'mine', '.'],
#    'french_tokens': ['ce', 'sont', 'les', 'miens', '.']},
#   {'english_tokens': ['they', "'re", 'mine', '.'],
#    'french_tokens': ['ce', 'sont', 'les', 'miennes', '.']},
#   {'english_tokens': ['they', "'re", 'mine', '.'],
#    'french_tokens': ['elles', 'sont', 'miennes', '.']},
#   {'english_tokens': ['they', "'re", 'mine', '.'],
#    'french_tokens': ['elles', 'sont', 'à', 'moi', '.']},
#   {'english_tokens': ['they', "'re", 'rich', '.'],
#    'french_tokens': ['ils', 'sont', 'riches', '.']},
#   {'english_tokens': ['they', "'re", 'rich', '.'],
#    'french_tokens': ['elles', 'sont', 'riches', '.']},
#   {'english_tokens': ['they', "'re", 'weak', '.'],
#    'french_tokens': ['ils', 'sont', 'faibles', '.']},
#   {'english_tokens': ['they', "'re", 'weak', '.'],
#    'french_tokens': ['elles', 'sont', 'faibles', '.']},
#   {'english_tokens': ['they', "'re", 'asian', '.'],
#    'french_tokens': ['ils', 'sont', 'asiatiques', '.']},
#   {'english_tokens': ['they', "'re", 'asian', '.'],
#    'french_tokens': ['elles', 'sont', 'asiatiques', '.']},
#   {'english_tokens': ['they', "'re", 'alive', '.'],
#    'french_tokens': ['ils', 'sont', 'en', 'vie', '.']},
#   {'english_tokens': ['they', "'re", 'angry', '.'],
#    'french_tokens': ['ils', 'sont', 'en', 'colère', '.']},
#   {'english_tokens': ['they', "'re", 'angry', '.'],
#    'french_tokens': ['elles', 'sont', 'en', 'colère', '.']},
#   {'english_tokens': ['they', "'re", 'armed', '.'],
#    'french_tokens': ['ils', 'sont', 'armés', '.']},
#   {'english_tokens': ['they', "'re", 'armed', '.'],
#    'french_tokens': ['elles', 'sont', 'armées', '.']},
#   {'english_tokens': ['they', "'re", 'awake', '.'],
#    'french_tokens': ['ils', 'sont', 'éveillés', '.']},
#   {'english_tokens': ['they', "'re", 'awake', '.'],
#    'french_tokens': ['elles', 'sont', 'éveillées', '.']},
#   {'english_tokens': ['they', "'re", 'brave', '.'],
#    'french_tokens': ['ils', 'sont', 'courageux', '.']},
#   {'english_tokens': ['they', "'re", 'brave', '.'],
#    'french_tokens': ['elles', 'sont', 'courageuses', '.']},
#   {'english_tokens': ['they', "'re", 'brave', '.'],
#    'french_tokens': ['ils', "n'ont", 'pas', 'froid', 'aux', 'yeux', '.']},
#   {'english_tokens': ['they', "'re", 'broke', '.'],
#    'french_tokens': ['ils', 'sont', 'fauchés', '.']},
#   {'english_tokens': ['they', "'re", 'broke', '.'],
#    'french_tokens': ['elles', 'sont', 'fauchées', '.']},
#   {'english_tokens': ['they', "'re", 'clean', '.'],
#    'french_tokens': ['ils', 'sont', 'propres', '.']},
#   {'english_tokens': ['they', "'re", 'clean', '.'],
#    'french_tokens': ['elles', 'sont', 'propres', '.']},
#   {'english_tokens': ['they', "'re", 'crazy', '.'],
#    'french_tokens': ['ils', 'sont', 'fous', '.']},
#   {'english_tokens': ['they', "'re", 'crazy', '.'],
#    'french_tokens': ['elles', 'sont', 'folles', '.']},
#   {'english_tokens': ['they', "'re", 'drunk', '.'],
#    'french_tokens': ['ils', 'sont', 'saouls', '.']},
#   {'english_tokens': ['they', "'re", 'drunk', '.'],
#    'french_tokens': ['elles', 'sont', 'saoules', '.']},
#   {'english_tokens': ['they', "'re", 'dying', '.'],
#    'french_tokens': ['ils', 'sont', 'en', 'train', 'de', 'mourir', '.']},
#   {'english_tokens': ['they', "'re", 'dying', '.'],
#    'french_tokens': ['elles', 'sont', 'en', 'train', 'de', 'mourir', '.']},
#   {'english_tokens': ['they', "'re", 'early', '.'],
#    'french_tokens': ['ils', 'sont', 'en', 'avance', '.']},
#   {'english_tokens': ['they', "'re", 'early', '.'],
#    'french_tokens': ['elles', 'sont', 'en', 'avance', '.']},
#   {'english_tokens': ['they', "'re", 'happy', '.'],
#    'french_tokens': ['elles', 'sont', 'heureuses', '.']},
#   {'english_tokens': ['they', "'re", 'lying', '.'],
#    'french_tokens': ['ils', 'mentent', '.']},
#   {'english_tokens': ['they', "'re", 'lying', '.'],
#    'french_tokens': ['elles', 'mentent', '.']},
#   {'english_tokens': ['they', "'re", 'small', '.'],
#    'french_tokens': ['ils', 'sont', 'petits', '.']},
#   {'english_tokens': ['they', "'re", 'small', '.'],
#    'french_tokens': ['elles', 'sont', 'petites', '.']},
#   {'english_tokens': ['they', "'re", 'spies', '.'],
#    'french_tokens': ['ce', 'sont', 'des', 'espions', '.']},
#   {'english_tokens': ['they', "'re", 'spies', '.'],
#    'french_tokens': ['ce', 'sont', 'des', 'espionnes', '.']},
#   {'english_tokens': ['they', "'re", 'there', '.'],
#    'french_tokens': ['ils', 'sont', 'là', '.']},
#   {'english_tokens': ['they', "'re", 'tired', '.'],
#    'french_tokens': ['ils', 'sont', 'fatigués', '.']},
#   {'english_tokens': ['they', "'re", 'tired', '.'],
#    'french_tokens': ['elles', 'sont', 'fatiguées', '.']},
#   {'english_tokens': ['they', "'re", 'wrong', '.'],
#    'french_tokens': ['ils', 'ont', 'tort', '!']},
#   {'english_tokens': ['they', "'re", 'asleep', '.'],
#    'french_tokens': ['ils', 'sont', 'endormis', '.']},
#   {'english_tokens': ['they', "'re", 'asleep', '.'],
#    'french_tokens': ['elles', 'sont', 'endormies', '.']},
#   {'english_tokens': ['they', "'re", 'babies', '.'],
#    'french_tokens': ['ce', 'sont', 'des', 'bébés', '.']},
#   {'english_tokens': ['they', "'re", 'boring', '.'],
#    'french_tokens': ['ils', 'sont', 'ennuyeux', '.']},
#   {'english_tokens': ['they', "'re", 'boring', '.'],
#    'french_tokens': ['elles', 'sont', 'ennuyeuses', '.']},
#   {'english_tokens': ['they', "'re", 'coming', '.'],
#    'french_tokens': ['ils', 'arrivent', '.']},
#   {'english_tokens': ['they', "'re", 'coming', '.'],
#    'french_tokens': ['elles', 'arrivent', '.']},
#   {'english_tokens': ['they', "'re", 'coming', '.'],
#    'french_tokens': ['ils', 'sont', 'en', 'train', "d'arriver", '.']},
#   {'english_tokens': ['they', "'re", 'coming', '.'],
#    'french_tokens': ['elles', 'sont', 'en', 'train', "d'arriver", '.']},
#   {'english_tokens': ['they', "'re", 'idiots', '.'],
#    'french_tokens': ['ils', 'sont', 'idiots', '.']},
#   {'english_tokens': ['they', "'re", 'inside', '.'],
#    'french_tokens': ['ils', 'sont', 'à', "l'intérieur", '.']},
#   {'english_tokens': ['they', "'re", 'strong', '.'],
#    'french_tokens': ['ils', 'sont', 'forts', '.']},
#   {'english_tokens': ['they', "'re", 'strong', '.'],
#    'french_tokens': ['elles', 'sont', 'fortes', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'bad', '.'],
#    'french_tokens': ['ils', 'sont', 'tous', 'mauvais', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'bad', '.'],
#    'french_tokens': ['elles', 'sont', 'toutes', 'mauvaises', '.']},
#   {'english_tokens': ['they', "'re", 'amazing', '.'],
#    'french_tokens': ['ils', 'sont', 'incroyables', '.']},
#   {'english_tokens': ['they', "'re", 'amazing', '.'],
#    'french_tokens': ['elles', 'sont', 'incroyables', '.']},
#   {'english_tokens': ['they', "'re", 'animals', '.'],
#    'french_tokens': ['ce', 'sont', 'des', 'animaux', '.']},
#   {'english_tokens': ['they', "'re", 'arguing', '.'],
#    'french_tokens': ['ils',
#     'sont',
#     'en',
#     'train',
#     'de',
#     'se',
#     'disputer',
#     '.']},
#   {'english_tokens': ['they', "'re", 'arguing', '.'],
#    'french_tokens': ['elles',
#     'sont',
#     'en',
#     'train',
#     'de',
#     'se',
#     'disputer',
#     '.']},
#   {'english_tokens': ['they', "'re", 'cousins', '.'],
#    'french_tokens': ['ils', 'sont', 'cousins', '.']},
#   {'english_tokens': ['they', "'re", 'cousins', '.'],
#    'french_tokens': ['elles', 'sont', 'cousines', '.']},
#   {'english_tokens': ['they', "'re", 'dancing', '.'],
#    'french_tokens': ['ils', 'sont', 'en', 'train', 'de', 'danser', '.']},
#   {'english_tokens': ['they', "'re", 'dancing', '.'],
#    'french_tokens': ['elles', 'sont', 'en', 'train', 'de', 'danser', '.']},
#   {'english_tokens': ['they', "'re", 'doctors', '.'],
#    'french_tokens': ['ils', 'sont', 'médecins', '.']},
#   {'english_tokens': ['they', "'re", 'doctors', '.'],
#    'french_tokens': ['elles', 'sont', 'médecins', '.']},
#   {'english_tokens': ['they', "'re", 'jittery', '.'],
#    'french_tokens': ['ils', 'sont', 'nerveux', '.']},
#   {'english_tokens': ['they', "'re", 'jittery', '.'],
#    'french_tokens': ['elles', 'sont', 'nerveuses', '.']},
#   {'english_tokens': ['they', "'re", 'jittery', '.'],
#    'french_tokens': ['ils', 'ont', 'la', 'frousse', '.']},
#   {'english_tokens': ['they', "'re", 'jittery', '.'],
#    'french_tokens': ['elles', 'ont', 'la', 'frousse', '.']},
#   {'english_tokens': ['they', "'re", 'leaving', '.'],
#    'french_tokens': ['ils', 'partent', '.']},
#   {'english_tokens': ['they', "'re", 'leaving', '.'],
#    'french_tokens': ['ils', "s'en", 'vont', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'bad', '.'],
#    'french_tokens': ['ils', 'ne', 'sont', 'pas', 'mal', '.']},
#   {'english_tokens': ['they', "'re", 'outside', '.'],
#    'french_tokens': ['ils', 'sont', 'dehors', '.']},
#   {'english_tokens': ['they', "'re", 'outside', '.'],
#    'french_tokens': ['ils', 'sont', 'à', "l'extérieur", '.']},
#   {'english_tokens': ['they', "'re", 'similar', '.'],
#    'french_tokens': ['ils', 'sont', 'similaires', '.']},
#   {'english_tokens': ['they', "'re", 'similar', '.'],
#    'french_tokens': ['elles', 'sont', 'similaires', '.']},
#   {'english_tokens': ['they', "'re", 'similar', '.'],
#    'french_tokens': ['ils', 'sont', 'semblables', '.']},
#   {'english_tokens': ['they', "'re", 'similar', '.'],
#    'french_tokens': ['elles', 'sont', 'semblables', '.']},
#   {'english_tokens': ['they', "'re", 'smiling', '.'],
#    'french_tokens': ['ils', 'sourient', '.']},
#   {'english_tokens': ['they', "'re", 'special', '.'],
#    'french_tokens': ['ils', 'sont', 'spéciaux', '.']},
#   {'english_tokens': ['they', "'re", 'special', '.'],
#    'french_tokens': ['elles', 'sont', 'spéciales', '.']},
#   {'english_tokens': ['they', "'re", 'staying', '.'],
#    'french_tokens': ['ils', 'restent', '.']},
#   {'english_tokens': ['they', "'re", 'staying', '.'],
#    'french_tokens': ['elles', 'restent', '.']},
#   {'english_tokens': ['they', "'re", 'talking', '.'],
#    'french_tokens': ['ils', 'parlent', '.']},
#   {'english_tokens': ['they', "'re", 'talking', '.'],
#    'french_tokens': ['elles', 'parlent', '.']},
#   {'english_tokens': ['they', "'re", 'too', 'fat', '.'],
#    'french_tokens': ['ils', 'sont', 'trop', 'gros', '.']},
#   {'english_tokens': ['they', "'re", 'too', 'fat', '.'],
#    'french_tokens': ['ils', 'sont', 'trop', 'gras', '.']},
#   {'english_tokens': ['they', "'re", 'too', 'fat', '.'],
#    'french_tokens': ['elles', 'sont', 'trop', 'grosses', '.']},
#   {'english_tokens': ['they', "'re", 'too', 'fat', '.'],
#    'french_tokens': ['elles', 'sont', 'trop', 'grasses', '.']},
#   {'english_tokens': ['they', "'re", 'useless', '.'],
#    'french_tokens': ['ils', 'sont', 'inutiles', '.']},
#   {'english_tokens': ['they', "'re", 'useless', '.'],
#    'french_tokens': ['elles', 'sont', 'inutiles', '.']},
#   {'english_tokens': ['they', "'re", 'with', 'me', '.'],
#    'french_tokens': ['ils', 'sont', 'avec', 'moi', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'dead', '.'],
#    'french_tokens': ['ils', 'sont', 'tous', 'morts', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'dead', '.'],
#    'french_tokens': ['ils', 'sont', 'tous', 'décédés', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'dead', '.'],
#    'french_tokens': ['elles', 'sont', 'toutes', 'décédées', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'dead', '.'],
#    'french_tokens': ['elles', 'sont', 'toutes', 'mortes', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'fake', '.'],
#    'french_tokens': ['ils', 'sont', 'tous', 'faux', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'fake', '.'],
#    'french_tokens': ['elles', 'sont', 'toutes', 'fausses', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'gone', '.'],
#    'french_tokens': ['ils', 'sont', 'tous', 'partis', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'gone', '.'],
#    'french_tokens': ['elles', 'sont', 'toutes', 'parties', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'gone', '.'],
#    'french_tokens': ['ils', 'ont', 'tous', 'disparu', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'gone', '.'],
#    'french_tokens': ['elles', 'ont', 'toutes', 'disparu', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'here', '.'],
#    'french_tokens': ['ils', 'sont', 'tous', 'là', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'here', '.'],
#    'french_tokens': ['elles', 'sont', 'toutes', 'là', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'here', '.'],
#    'french_tokens': ['ils', 'sont', 'tous', 'ici', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'here', '.'],
#    'french_tokens': ['elles', 'sont', 'toutes', 'ici', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'mine', '.'],
#    'french_tokens': ['ils', 'sont', 'tous', 'à', 'moi', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'mine', '.'],
#    'french_tokens': ['elles', 'sont', 'toutes', 'à', 'moi', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'mine', '.'],
#    'french_tokens': ['ce', 'sont', 'tous', 'les', 'miens', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'mine', '.'],
#    'french_tokens': ['ce', 'sont', 'toutes', 'les', 'miennes', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'nuts', '.'],
#    'french_tokens': ['ils', 'sont', 'tous', 'dingues', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'nuts', '.'],
#    'french_tokens': ['elles', 'sont', 'toutes', 'dingues', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'safe', '.'],
#    'french_tokens': ['ils', 'sont', 'tous', 'en', 'sécurité', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'safe', '.'],
#    'french_tokens': ['elles', 'sont', 'toutes', 'en', 'sécurité', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'dead', '.'],
#    'french_tokens': ['ils', 'ne', 'sont', 'pas', 'morts', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'dead', '.'],
#    'french_tokens': ['elles', 'ne', 'sont', 'pas', 'mortes', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'evil', '.'],
#    'french_tokens': ['ils', 'ne', 'sont', 'pas', 'mauvais', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'evil', '.'],
#    'french_tokens': ['elles', 'ne', 'sont', 'pas', 'mauvaises', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'mine', '.'],
#    'french_tokens': ['ce', 'ne', 'sont', 'pas', 'les', 'miens', '.']},
#   {'english_tokens': ['they', "'re", 'so', 'funny', '.'],
#    'french_tokens': ['ils', 'sont', 'si', 'drôles', '.']},
#   {'english_tokens': ['they', "'re", 'stalling', '.'],
#    'french_tokens': ['ils', 'sont', 'en', 'train', 'de', 'temporiser', '.']},
#   {'english_tokens': ['they', "'re", 'stalling', '.'],
#    'french_tokens': ['ils',
#     'sont',
#     'en',
#     'train',
#     'de',
#     'gagner',
#     'du',
#     'temps',
#     '.']},
#   {'english_tokens': ['they', "'re", 'stalling', '.'],
#    'french_tokens': ['elles',
#     'sont',
#     'en',
#     'train',
#     'de',
#     'gagner',
#     'du',
#     'temps',
#     '.']},
#   {'english_tokens': ['they', "'re", 'stalling', '.'],
#    'french_tokens': ['elles', 'sont', 'en', 'train', 'de', 'temporiser', '.']},
#   {'english_tokens': ['they', "'re", 'students', '.'],
#    'french_tokens': ['ce', 'sont', 'des', 'étudiants', '.']},
#   {'english_tokens': ['they', "'re", 'students', '.'],
#    'french_tokens': ['ce', 'sont', 'des', 'étudiantes', '.']},
#   {'english_tokens': ['they', "'re", 'students', '.'],
#    'french_tokens': ['ce', 'sont', 'des', 'élèves', '.']},
#   {'english_tokens': ['they', "'re", 'students', '.'],
#    'french_tokens': ['elles', 'sont', 'étudiantes', '.']},
#   {'english_tokens': ['they', "'re", 'students', '.'],
#    'french_tokens': ['ils', 'sont', 'étudiants', '.']},
#   {'english_tokens': ['they', "'re", 'traitors', '.'],
#    'french_tokens': ['ce', 'sont', 'des', 'traîtres', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'alike', '.'],
#    'french_tokens': ['ils', 'sont', 'tous', 'semblables', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'alike', '.'],
#    'french_tokens': ['elles', 'sont', 'toutes', 'semblables', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'liars', '.'],
#    'french_tokens': ['ce', 'sont', 'tous', 'des', 'menteurs', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'liars', '.'],
#    'french_tokens': ['ce', 'sont', 'toutes', 'des', 'menteuses', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'lying', '.'],
#    'french_tokens': ['elles', 'mentent', 'toutes', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'lying', '.'],
#    'french_tokens': ['ils', 'mentent', 'tous', '.']},
#   {'english_tokens': ['they', "'re", 'cannibals', '.'],
#    'french_tokens': ['ce', 'sont', 'des', 'cannibales', '.']},
#   {'english_tokens': ['they', "'re", 'dangerous', '.'],
#    'french_tokens': ['ils', 'sont', 'dangereux', '.']},
#   {'english_tokens': ['they', "'re", 'dangerous', '.'],
#    'french_tokens': ['elles', 'sont', 'dangereuses', '.']},
#   {'english_tokens': ['they', "'re", 'different', '.'],
#    'french_tokens': ['ils', 'sont', 'différents', '.']},
#   {'english_tokens': ['they', "'re", 'different', '.'],
#    'french_tokens': ['elles', 'sont', 'différentes', '.']},
#   {'english_tokens': ['they', "'re", 'expensive', '.'],
#    'french_tokens': ['ils', 'sont', 'onéreux', '.']},
#   {'english_tokens': ['they', "'re", 'expensive', '.'],
#    'french_tokens': ['elles', 'sont', 'onéreuses', '.']},
#   {'english_tokens': ['they', "'re", 'in', 'danger', '.'],
#    'french_tokens': ['ils', 'sont', 'en', 'danger', '.']},
#   {'english_tokens': ['they', "'re", 'in', 'danger', '.'],
#    'french_tokens': ['elles', 'sont', 'en', 'danger', '.']},
#   {'english_tokens': ['they', "'re", 'nice', 'guys', '.'],
#    'french_tokens': ['ce', 'sont', 'de', 'chics', 'types', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'alone', '.'],
#    'french_tokens': ['ils', 'ne', 'sont', 'pas', 'seuls', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'alone', '.'],
#    'french_tokens': ['elles', 'ne', 'sont', 'pas', 'seules', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'happy', '.'],
#    'french_tokens': ['ils', 'ne', 'sont', 'pas', 'satisfaits', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'happy', '.'],
#    'french_tokens': ['elles', 'ne', 'sont', 'pas', 'satisfaites', '.']},
#   {'english_tokens': ['they', "'re", 'surprised', '.'],
#    'french_tokens': ['ils', 'sont', 'surpris', '.']},
#   {'english_tokens': ['they', "'re", 'surprised', '.'],
#    'french_tokens': ['elles', 'sont', 'surprises', '.']},
#   {'english_tokens': ['they', "'re", 'undamaged', '.'],
#    'french_tokens': ['ils', 'sont', 'intacts', '.']},
#   {'english_tokens': ['they', "'re", 'undamaged', '.'],
#    'french_tokens': ['elles', 'sont', 'intactes', '.']},
#   {'english_tokens': ['they', "'re", 'very', 'busy', '.'],
#    'french_tokens': ['ils', 'sont', 'très', 'occupés', '.']},
#   {'english_tokens': ['they', "'re", 'very', 'busy', '.'],
#    'french_tokens': ['elles', 'sont', 'très', 'occupées', '.']},
#   {'english_tokens': ['they', "'re", 'christians', '.'],
#    'french_tokens': ['ils', 'sont', 'chrétiens', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'guilty', '.'],
#    'french_tokens': ['ils', 'sont', 'tous', 'coupables', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'guilty', '.'],
#    'french_tokens': ['elles', 'sont', 'toutes', 'coupables', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'hungry', '.'],
#    'french_tokens': ['ils', 'ont', 'tous', 'faim', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'hungry', '.'],
#    'french_tokens': ['elles', 'ont', 'toutes', 'faim', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'normal', '.'],
#    'french_tokens': ['ils', 'sont', 'tous', 'normaux', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'normal', '.'],
#    'french_tokens': ['elles', 'sont', 'toutes', 'normales', '.']},
#   {'english_tokens': ['they', "'re", 'both', 'right', '.'],
#    'french_tokens': ['ils', 'ont', 'tous', 'les', 'deux', 'raison', '.']},
#   {'english_tokens': ['they', "'re", 'both', 'right', '.'],
#    'french_tokens': ['elles', 'ont', 'toutes', 'les', 'deux', 'raison', '.']},
#   {'english_tokens': ['they', "'re", 'carnations', '.'],
#    'french_tokens': ['ce', 'sont', 'des', 'œillets', '.']},
#   {'english_tokens': ['they', "'re", 'disposable', '.'],
#    'french_tokens': ['ils', 'sont', 'jetables', '.']},
#   {'english_tokens': ['they', "'re", 'disposable', '.'],
#    'french_tokens': ['elles', 'sont', 'jetables', '.']},
#   {'english_tokens': ['they', "'re", 'downstairs', '.'],
#    'french_tokens': ['ils', 'sont', 'en', 'bas', '.']},
#   {'english_tokens': ['they', "'re", 'downstairs', '.'],
#    'french_tokens': ['ils', 'sont', 'en-dessous', '.']},
#   {'english_tokens': ['they', "'re", 'downstairs', '.'],
#    'french_tokens': ['ils', 'sont', 'au-dessous', '.']},
#   {'english_tokens': ['they', "'re", 'in', 'trouble', '.'],
#    'french_tokens': ['ils', 'ont', 'des', 'ennuis', '.']},
#   {'english_tokens': ['they', "'re", 'in', 'trouble', '.'],
#    'french_tokens': ['elles', 'ont', 'des', 'ennuis', '.']},
#   {'english_tokens': ['they', "'re", 'in', 'trouble', '.'],
#    'french_tokens': ['ils', 'sont', 'dans', 'la', 'mouise', '.']},
#   {'english_tokens': ['they', "'re", 'in', 'trouble', '.'],
#    'french_tokens': ['elles', 'sont', 'dans', 'la', 'mouise', '.']},
#   {'english_tokens': ['they', "'re", 'just', 'words', '.'],
#    'french_tokens': ['ce', 'ne', 'sont', 'que', 'des', 'mots', '.']},
#   {'english_tokens': ['they', "'re", 'mad', 'at', 'you', '.'],
#    'french_tokens': ['ils', 'sont', 'en', 'colère', 'après', 'toi', '.']},
#   {'english_tokens': ['they', "'re", 'mad', 'at', 'you', '.'],
#    'french_tokens': ['ils', 'sont', 'en', 'colère', 'après', 'vous', '.']},
#   {'english_tokens': ['they', "'re", 'mad', 'at', 'you', '.'],
#    'french_tokens': ['elles', 'sont', 'en', 'colère', 'après', 'toi', '.']},
#   {'english_tokens': ['they', "'re", 'mad', 'at', 'you', '.'],
#    'french_tokens': ['elles', 'sont', 'en', 'colère', 'après', 'vous', '.']},
#   {'english_tokens': ['they', "'re", 'mad', 'at', 'you', '.'],
#    'french_tokens': ['elles', 'sont', 'furieuses', 'après', 'vous', '.']},
#   {'english_tokens': ['they', "'re", 'mad', 'at', 'you', '.'],
#    'french_tokens': ['elles', 'sont', 'furieuses', 'après', 'toi', '.']},
#   {'english_tokens': ['they', "'re", 'mad', 'at', 'you', '.'],
#    'french_tokens': ['ils', 'sont', 'furieux', 'après', 'vous', '.']},
#   {'english_tokens': ['they', "'re", 'mad', 'at', 'you', '.'],
#    'french_tokens': ['ils', 'sont', 'furieux', 'après', 'toi', '.']},
#   {'english_tokens': ['they', "'re", 'my', 'friends', '.'],
#    'french_tokens': ['ils', 'sont', 'mes', 'amis', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'coming', '.'],
#    'french_tokens': ['ils', 'ne', 'viennent', 'pas', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'coming', '.'],
#    'french_tokens': ['elles', 'ne', 'viennent', 'pas', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'so', 'bad', '.'],
#    'french_tokens': ['ils', 'ne', 'sont', 'pas', 'si', 'mauvais', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'so', 'bad', '.'],
#    'french_tokens': ['elles', 'ne', 'sont', 'pas', 'si', 'mauvaises', '.']},
#   {'english_tokens': ['they', "'re", 'part', 'of', 'us', '.'],
#    'french_tokens': ['ils', 'font', 'partie', 'de', 'nous', '.']},
#   {'english_tokens': ['they', "'re", 'part', 'of', 'us', '.'],
#    'french_tokens': ['elles', 'font', 'partie', 'de', 'nous', '.']},
#   {'english_tokens': ['they', "'re", 'very', 'smart', '.'],
#    'french_tokens': ['ils', 'sont', 'très', 'intelligents', '.']},
#   {'english_tokens': ['they', "'re", 'very', 'smart', '.'],
#    'french_tokens': ['elles', 'sont', 'très', 'intelligentes', '.']},
#   {'english_tokens': ['they', "'re", 'a', 'good', 'team', '.'],
#    'french_tokens': ['ils', 'sont', 'une', 'bonne', 'équipe', '.']},
#   {'english_tokens': ['they', "'re", 'about', 'to', 'go', '.'],
#    'french_tokens': ['ils',
#     'sont',
#     'sur',
#     'le',
#     'point',
#     'de',
#     'partir',
#     '.']},
#   {'english_tokens': ['they', "'re", 'all', 'thieves', '.'],
#    'french_tokens': ['ce', 'sont', 'tous', 'des', 'voleurs', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'thieves', '.'],
#    'french_tokens': ['ce', 'sont', 'toutes', 'des', 'voleuses', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'waiting', '.'],
#    'french_tokens': ['ils', 'attendent', 'tous', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'waiting', '.'],
#    'french_tokens': ['elles', 'attendent', 'toutes', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'waiting', '.'],
#    'french_tokens': ['elles',
#     'sont',
#     'toutes',
#     'en',
#     'train',
#     "d'attendre",
#     '.']},
#   {'english_tokens': ['they', "'re", 'all', 'waiting', '.'],
#    'french_tokens': ['ils', 'sont', 'tous', 'en', 'train', "d'attendre", '.']},
#   {'english_tokens': ['they', "'re", 'almost', 'here', '.'],
#    'french_tokens': ['ils', 'sont', 'presque', 'là', '.']},
#   {'english_tokens': ['they', "'re", 'almost', 'here', '.'],
#    'french_tokens': ['ils', 'en', 'sont', 'presque', 'là', '.']},
#   {'english_tokens': ['they', "'re", 'almost', 'here', '.'],
#    'french_tokens': ['elles', 'sont', 'presque', 'là', '.']},
#   {'english_tokens': ['they', "'re", 'almost', 'here', '.'],
#    'french_tokens': ['elles', 'en', 'sont', 'presque', 'là', '.']},
#   {'english_tokens': ['they', "'re", 'here', 'for', 'me', '.'],
#    'french_tokens': ['ils', 'sont', 'là', 'pour', 'moi', '.']},
#   {'english_tokens': ['they', "'re", 'here', 'for', 'me', '.'],
#    'french_tokens': ['elles', 'sont', 'là', 'pour', 'moi', '.']},
#   {'english_tokens': ['they', "'re", 'ignoring', 'me', '.'],
#    'french_tokens': ['ils', 'ne', 'me', 'prêtent', 'pas', 'attention', '.']},
#   {'english_tokens': ['they', "'re", 'kind', 'of', 'fun', '.'],
#    'french_tokens': ['ils', 'sont', 'plutôt', 'marrants', '.']},
#   {'english_tokens': ['they', "'re", 'kind', 'of', 'fun', '.'],
#    'french_tokens': ['elles', 'sont', 'plutôt', 'marrantes', '.']},
#   {'english_tokens': ['they', "'re", 'out', 'of', 'town', '.'],
#    'french_tokens': ['ils', 'ne', 'sont', 'pas', 'en', 'ville', '.']},
#   {'english_tokens': ['they', "'re", 'out', 'of', 'town', '.'],
#    'french_tokens': ['elles', 'ne', 'sont', 'pas', 'en', 'ville', '.']},
#   {'english_tokens': ['they', "'re", 'really', 'ugly', '.'],
#    'french_tokens': ['ils', 'sont', 'vraiment', 'moches', '.']},
#   {'english_tokens': ['they', "'re", 'really', 'ugly', '.'],
#    'french_tokens': ['elles', 'sont', 'vraiment', 'moches', '.']},
#   {'english_tokens': ['they', "'re", 'still', 'young', '.'],
#    'french_tokens': ['ils', 'sont', 'encore', 'jeunes', '.']},
#   {'english_tokens': ['they', "'re", 'still', 'young', '.'],
#    'french_tokens': ['elles', 'sont', 'encore', 'jeunes', '.']},
#   {'english_tokens': ['they', "'re", 'able', 'to', 'sing', '.'],
#    'french_tokens': ['ils', 'peuvent', 'chanter', '.']},
#   {'english_tokens': ['they', "'re", 'able', 'to', 'sing', '.'],
#    'french_tokens': ['ils', 'sont', 'capables', 'de', 'chanter', '.']},
#   {'english_tokens': ['they', "'re", 'afraid', 'of', 'me', '.'],
#    'french_tokens': ['elles', 'ont', 'peur', 'de', 'moi', '.']},
#   {'english_tokens': ['they', "'re", 'afraid', 'of', 'me', '.'],
#    'french_tokens': ['ils', 'ont', 'peur', 'de', 'moi', '.']},
#   {'english_tokens': ['they', "'re", 'afraid', 'of', 'us', '.'],
#    'french_tokens': ['elles', 'ont', 'peur', 'de', 'nous', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'in', 'there', '.'],
#    'french_tokens': ['ils', 'sont', 'tous', 'là-dedans', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'in', 'there', '.'],
#    'french_tokens': ['elles', 'sont', 'toutes', 'là-dedans', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'the', 'same', '.'],
#    'french_tokens': ['ils', 'sont', 'tous', 'les', 'mêmes', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'the', 'same', '.'],
#    'french_tokens': ['elles', 'sont', 'toutes', 'les', 'mêmes', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'tourists', '.'],
#    'french_tokens': ['ce', 'sont', 'tous', 'des', 'touristes', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'tourists', '.'],
#    'french_tokens': ['ce', 'sont', 'toutes', 'des', 'touristes', '.']},
#   {'english_tokens': ['they', "'re", 'going', 'to', 'try', '.'],
#    'french_tokens': ['ils', 'vont', 'essayer', '.']},
#   {'english_tokens': ['they', "'re", 'going', 'to', 'try', '.'],
#    'french_tokens': ['elles', 'vont', 'essayer', '.']},
#   {'english_tokens': ['they', "'re", 'going', 'to', 'try', '.'],
#    'french_tokens': ['ils', 'vont', 'le', 'tenter', '.']},
#   {'english_tokens': ['they', "'re", 'going', 'to', 'try', '.'],
#    'french_tokens': ['elles', 'vont', 'le', 'tenter', '.']},
#   {'english_tokens': ['they', "'re", 'hard', 'to', 'find', '.'],
#    'french_tokens': ['ils', 'sont', 'durs', 'à', 'trouver', '.']},
#   {'english_tokens': ['they', "'re", 'hard', 'to', 'find', '.'],
#    'french_tokens': ['elles', 'sont', 'dures', 'à', 'trouver', '.']},
#   {'english_tokens': ['they', "'re", 'just', 'for', 'you', '.'],
#    'french_tokens': ['ils', 'sont', 'juste', 'pour', 'toi', '.']},
#   {'english_tokens': ['they', "'re", 'just', 'for', 'you', '.'],
#    'french_tokens': ['elles', 'sont', 'juste', 'pour', 'toi', '.']},
#   {'english_tokens': ['they', "'re", 'just', 'for', 'you', '.'],
#    'french_tokens': ['ils', 'sont', 'juste', 'pour', 'vous', '.']},
#   {'english_tokens': ['they', "'re", 'just', 'for', 'you', '.'],
#    'french_tokens': ['elles', 'sont', 'juste', 'pour', 'vous', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'a', 'threat', '.'],
#    'french_tokens': ['ils', 'ne', 'constituent', 'pas', 'une', 'menace', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'a', 'threat', '.'],
#    'french_tokens': ['elles',
#     'ne',
#     'constituent',
#     'pas',
#     'une',
#     'menace',
#     '.']},
#   {'english_tokens': ['they', "'re", 'not', 'all', 'busy', '.'],
#    'french_tokens': ['ils', 'ne', 'sont', 'pas', 'tous', 'occupés', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'all', 'busy', '.'],
#    'french_tokens': ['elles', 'ne', 'sont', 'pas', 'toutes', 'occupées', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'here', 'yet', '.'],
#    'french_tokens': ['elles', 'ne', 'sont', 'pas', 'encore', 'là', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'home', 'yet', '.'],
#    'french_tokens': ['ils',
#     'ne',
#     'sont',
#     'pas',
#     'encore',
#     'chez',
#     'eux',
#     '.']},
#   {'english_tokens': ['they', "'re", 'not', 'home', 'yet', '.'],
#    'french_tokens': ['elles',
#     'ne',
#     'sont',
#     'pas',
#     'encore',
#     'chez',
#     'elles',
#     '.']},
#   {'english_tokens': ['they', "'re", 'not', 'home', 'yet', '.'],
#    'french_tokens': ['ils',
#     'ne',
#     'sont',
#     'pas',
#     'encore',
#     'à',
#     'la',
#     'maison',
#     '.']},
#   {'english_tokens': ['they', "'re", 'not', 'home', 'yet', '.'],
#    'french_tokens': ['elles',
#     'ne',
#     'sont',
#     'pas',
#     'encore',
#     'à',
#     'la',
#     'maison',
#     '.']},
#   {'english_tokens': ['they', "'re", 'not', 'my', 'rules', '.'],
#    'french_tokens': ['ce', 'ne', 'sont', 'pas', 'mes', 'règles', '.']},
#   {'english_tokens': ['they', "'re", 'really', 'tight', '.'],
#    'french_tokens': ['ils', 'sont', 'vraiment', 'intimes', '.']},
#   {'english_tokens': ['they', "'re", 'really', 'tight', '.'],
#    'french_tokens': ['ils', 'sont', 'vraiment', 'serrés', '.']},
#   {'english_tokens': ['they', "'re", 'really', 'tight', '.'],
#    'french_tokens': ['ils', 'sont', 'vraiment', 'radins', '.']},
#   {'english_tokens': ['they', "'re", 'sending', 'help', '.'],
#    'french_tokens': ['ils', 'envoient', 'de', "l'aide", '.']},
#   {'english_tokens': ['they', "'re", 'able', 'students', '.'],
#    'french_tokens': ['ce', 'sont', 'des', 'étudiants', 'capables', '.']},
#   {'english_tokens': ['they', "'re", 'afraid', 'of', 'him', '.'],
#    'french_tokens': ['elles', 'ont', 'peur', 'de', 'lui', '.']},
#   {'english_tokens': ['they', "'re", 'afraid', 'of', 'him', '.'],
#    'french_tokens': ['ils', 'ont', 'peur', 'de', 'lui', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'terrified', '.'],
#    'french_tokens': ['ils', 'sont', 'tous', 'terrifiés', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'terrified', '.'],
#    'french_tokens': ['elles', 'sont', 'toutes', 'terrifiées', '.']},
#   {'english_tokens': ['they', "'re", 'coming', 'for', 'me', '.'],
#    'french_tokens': ['ils', 'viennent', 'pour', 'moi', '.']},
#   {'english_tokens': ['they', "'re", 'coming', 'for', 'me', '.'],
#    'french_tokens': ['elles', 'viennent', 'pour', 'moi', '.']},
#   {'english_tokens': ['they', "'re", 'coming', 'for', 'us', '.'],
#    'french_tokens': ['ils', 'viennent', 'nous', 'chercher', '.']},
#   {'english_tokens': ['they', "'re", 'coming', 'for', 'us', '.'],
#    'french_tokens': ['elles', 'viennent', 'nous', 'chercher', '.']},
#   {'english_tokens': ['they', "'re", 'in', 'the', 'garden', '.'],
#    'french_tokens': ['ils', 'sont', 'au', 'jardin', '.']},
#   {'english_tokens': ['they', "'re", 'in', 'the', 'garden', '.'],
#    'french_tokens': ['elles', 'sont', 'au', 'jardin', '.']},
#   {'english_tokens': ['they', "'re", 'in', 'the', 'shower', '.'],
#    'french_tokens': ['ils', 'sont', 'dans', 'la', 'douche', '.']},
#   {'english_tokens': ['they', "'re", 'in', 'the', 'shower', '.'],
#    'french_tokens': ['elles', 'sont', 'dans', 'la', 'douche', '.']},
#   {'english_tokens': ['they', "'re", 'in', 'the', 'shower', '.'],
#    'french_tokens': ['elles', 'sont', 'sous', 'la', 'douche', '.']},
#   {'english_tokens': ['they', "'re", 'in', 'the', 'shower', '.'],
#    'french_tokens': ['ils', 'sont', 'sous', 'la', 'douche', '.']},
#   {'english_tokens': ['they', "'re", 'just', 'students', '.'],
#    'french_tokens': ['ce', 'sont', 'juste', 'des', 'étudiants', '.']},
#   {'english_tokens': ['they', "'re", 'just', 'students', '.'],
#    'french_tokens': ['ce', 'ne', 'sont', 'que', 'des', 'étudiants', '.']},
#   {'english_tokens': ['they', "'re", 'just', 'students', '.'],
#    'french_tokens': ['ce', 'ne', 'sont', 'que', 'des', 'étudiantes', '.']},
#   {'english_tokens': ['they', "'re", 'just', 'students', '.'],
#    'french_tokens': ['ce', 'sont', 'juste', 'des', 'étudiantes', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'criminals', '.'],
#    'french_tokens': ['ce', 'ne', 'sont', 'pas', 'des', 'criminels', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'criminals', '.'],
#    'french_tokens': ['ce', 'ne', 'sont', 'pas', 'des', 'criminelles', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'expensive', '.'],
#    'french_tokens': ['ils', 'ne', 'sont', 'pas', 'chers', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'expensive', '.'],
#    'french_tokens': ['elles', 'ne', 'sont', 'pas', 'chères', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'expensive', '.'],
#    'french_tokens': ['elles', 'ne', 'sont', 'pas', 'onéreuses', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'following', '.'],
#    'french_tokens': ['ils',
#     'ne',
#     'sont',
#     'pas',
#     'en',
#     'train',
#     'de',
#     'suivre',
#     '.']},
#   {'english_tokens': ['they', "'re", 'not', 'following', '.'],
#    'french_tokens': ['elles',
#     'ne',
#     'sont',
#     'pas',
#     'en',
#     'train',
#     'de',
#     'suivre',
#     '.']},
#   {'english_tokens': ['they', "'re", 'playing', 'chess', '.'],
#    'french_tokens': ['ils', 'jouent', 'aux', 'échecs', '.']},
#   {'english_tokens': ['they', "'re", 'up', 'to', 'no', 'good', '.'],
#    'french_tokens': ['ils', 'ne', 'mijotent', 'rien', 'de', 'bon', '.']},
#   {'english_tokens': ['they', "'re", 'up', 'to', 'no', 'good', '.'],
#    'french_tokens': ['ils', 'vont', 'faire', 'des', 'conneries', '.']},
#   {'english_tokens': ['they', "'re", 'up', 'to', 'no', 'good', '.'],
#    'french_tokens': ['ils', 'préparent', 'un', 'mauvais', 'tour', '.']},
#   {'english_tokens': ['they', "'re", 'up', 'to', 'no', 'good', '.'],
#    'french_tokens': ['ils',
#     'font',
#     'des',
#     'affaires',
#     'pas',
#     'correctes',
#     '.']},
#   {'english_tokens': ['they', "'re", 'about', 'to', 'leave', '.'],
#    'french_tokens': ['ils',
#     'sont',
#     'sur',
#     'le',
#     'point',
#     'de',
#     'partir',
#     '.']},
#   {'english_tokens': ['they', "'re", 'about', 'to', 'leave', '.'],
#    'french_tokens': ['elles',
#     'sont',
#     'sur',
#     'le',
#     'point',
#     'de',
#     'partir',
#     '.']},
#   {'english_tokens': ['they', "'re", 'all', 'against', 'me', '.'],
#    'french_tokens': ['elles', 'sont', 'toutes', 'contre', 'moi', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'against', 'me', '.'],
#    'french_tokens': ['ils', 'sont', 'tous', 'contre', 'moi', '.']},
#   {'english_tokens': ['they', "'re", 'doing', 'it', 'right', '.'],
#    'french_tokens': ['ils', 'le', 'font', 'correctement', '.']},
#   {'english_tokens': ['they', "'re", 'doing', 'it', 'right', '.'],
#    'french_tokens': ['elles', 'le', 'font', 'correctement', '.']},
#   {'english_tokens': ['they', "'re", 'doing', 'it', 'right', '.'],
#    'french_tokens': ['ils', 'le', 'font', 'comme', 'il', 'faut', '.']},
#   {'english_tokens': ['they', "'re", 'doing', 'it', 'right', '.'],
#    'french_tokens': ['elles', 'le', 'font', 'comme', 'il', 'faut', '.']},
#   {'english_tokens': ['they', "'re", 'in', 'the', 'hot', 'tub', '.'],
#    'french_tokens': ['ils',
#     'sont',
#     'dans',
#     'le',
#     'baquet',
#     "d'eau",
#     'chaude',
#     '.']},
#   {'english_tokens': ['they', "'re", 'in', 'the', 'hot', 'tub', '.'],
#    'french_tokens': ['elles',
#     'sont',
#     'dans',
#     'le',
#     'baquet',
#     "d'eau",
#     'chaude',
#     '.']},
#   {'english_tokens': ['they', "'re", 'not', 'my', 'friends', '.'],
#    'french_tokens': ['ce', 'ne', 'sont', 'pas', 'mes', 'amis', '.']},
#   {'english_tokens': ['they', "'re", 'out', 'to', 'get', 'you', '.'],
#    'french_tokens': ['ils', 'sont', 'à', 'vos', 'trousses', '.']},
#   {'english_tokens': ['they', "'re", 'out', 'to', 'get', 'you', '.'],
#    'french_tokens': ['ils', 'sont', 'à', 'tes', 'trousses', '.']},
#   {'english_tokens': ['they', "'re", 'out', 'to', 'get', 'you', '.'],
#    'french_tokens': ['elles', 'sont', 'à', 'vos', 'trousses', '.']},
#   {'english_tokens': ['they', "'re", 'out', 'to', 'get', 'you', '.'],
#    'french_tokens': ['elles', 'sont', 'à', 'tes', 'trousses', '.']},
#   {'english_tokens': ['they', "'re", 'still', 'not', 'safe', '.'],
#    'french_tokens': ['ils',
#     'ne',
#     'sont',
#     'toujours',
#     'pas',
#     'en',
#     'sécurité',
#     '.']},
#   {'english_tokens': ['they', "'re", 'still', 'not', 'safe', '.'],
#    'french_tokens': ['elles',
#     'ne',
#     'sont',
#     'toujours',
#     'pas',
#     'en',
#     'sécurité',
#     '.']},
#   {'english_tokens': ['they', "'re", 'still', 'together', '.'],
#    'french_tokens': ['ils', 'sont', 'toujours', 'ensemble', '.']},
#   {'english_tokens': ['they', "'re", 'still', 'together', '.'],
#    'french_tokens': ['elles', 'sont', 'toujours', 'ensemble', '.']},
#   {'english_tokens': ['they', "'re", 'waiting', 'for', 'us', '.'],
#    'french_tokens': ['ils', 'nous', 'attendent', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'on', 'vacation', '.'],
#    'french_tokens': ['ils', 'sont', 'tous', 'en', 'vacances', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'on', 'vacation', '.'],
#    'french_tokens': ['elles', 'sont', 'toutes', 'en', 'vacances', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'watching', 'tv', '.'],
#    'french_tokens': ['ils',
#     'sont',
#     'tous',
#     'en',
#     'train',
#     'de',
#     'regarder',
#     'la',
#     'télé',
#     '.']},
#   {'english_tokens': ['they', "'re", 'all', 'watching', 'tv', '.'],
#    'french_tokens': ['elles',
#     'sont',
#     'toutes',
#     'en',
#     'train',
#     'de',
#     'regarder',
#     'la',
#     'télé',
#     '.']},
#   {'english_tokens': ['they', "'re", 'all', 'watching', 'us', '.'],
#    'french_tokens': ['ils', 'nous', 'regardent', 'tous', '.']},
#   {'english_tokens': ['they', "'re", 'all', 'watching', 'us', '.'],
#    'french_tokens': ['elles',
#     'sont',
#     'toutes',
#     'en',
#     'train',
#     'de',
#     'nous',
#     'regarder',
#     '.']},
#   {'english_tokens': ['they', "'re", 'headed', 'this', 'way', '.'],
#    'french_tokens': ['ils', 'vont', 'dans', 'cette', 'direction', '.']},
#   {'english_tokens': ['they', "'re", 'headed', 'this', 'way', '.'],
#    'french_tokens': ['elles', 'vont', 'dans', 'cette', 'direction', '.']},
#   {'english_tokens': ['they', "'re", 'headed', 'this', 'way', '.'],
#    'french_tokens': ['ils',
#     'se',
#     'rendent',
#     'dans',
#     'cette',
#     'direction',
#     '.']},
#   {'english_tokens': ['they', "'re", 'headed', 'this', 'way', '.'],
#    'french_tokens': ['elles',
#     'se',
#     'rendent',
#     'dans',
#     'cette',
#     'direction',
#     '.']},
#   {'english_tokens': ['they', "'re", 'looking', 'for', 'tom', '.'],
#    'french_tokens': ['ils', 'cherchent', 'tom', '.']},
#   {'english_tokens': ['they', "'re", 'looking', 'for', 'tom', '.'],
#    'french_tokens': ['elles', 'cherchent', 'tom', '.']},
#   {'english_tokens': ['they', "'re", 'looking', 'for', 'you', '.'],
#    'french_tokens': ['ils', 'te', 'cherchent', '.']},
#   {'english_tokens': ['they', "'re", 'looking', 'for', 'you', '.'],
#    'french_tokens': ['ils', 'vous', 'cherchent', '.']},
#   {'english_tokens': ['they', "'re", 'looking', 'for', 'you', '.'],
#    'french_tokens': ['elles', 'te', 'cherchent', '.']},
#   {'english_tokens': ['they', "'re", 'looking', 'for', 'you', '.'],
#    'french_tokens': ['elles', 'vous', 'cherchent', '.']},
#   {'english_tokens': ['they', "'re", 'looking', 'for', 'you', '.'],
#    'french_tokens': ['ils',
#     'sont',
#     'en',
#     'train',
#     'de',
#     'te',
#     'chercher',
#     '.']},
#   {'english_tokens': ['they', "'re", 'looking', 'for', 'you', '.'],
#    'french_tokens': ['elles',
#     'sont',
#     'en',
#     'train',
#     'de',
#     'te',
#     'chercher',
#     '.']},
#   {'english_tokens': ['they', "'re", 'looking', 'for', 'you', '.'],
#    'french_tokens': ['elles',
#     'sont',
#     'en',
#     'train',
#     'de',
#     'vous',
#     'chercher',
#     '.']},
#   {'english_tokens': ['they', "'re", 'looking', 'for', 'you', '.'],
#    'french_tokens': ['ils',
#     'sont',
#     'en',
#     'train',
#     'de',
#     'vous',
#     'chercher',
#     '.']},
#   {'english_tokens': ['they', "'re", 'not', 'coming', 'back', '.'],
#    'french_tokens': ['ils', 'ne', 'vont', 'pas', 'revenir', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'coming', 'back', '.'],
#    'french_tokens': ['elles', 'ne', 'vont', 'pas', 'revenir', '.']},
#   {'english_tokens': ['they', "'re", 'right', 'behind', 'me', '.'],
#    'french_tokens': ['elles',
#     'se',
#     'trouvent',
#     'juste',
#     'derrière',
#     'moi',
#     '.']},
#   {'english_tokens': ['they', "'re", 'right', 'behind', 'me', '.'],
#    'french_tokens': ['ils',
#     'se',
#     'trouvent',
#     'juste',
#     'derrière',
#     'moi',
#     '.']},
#   {'english_tokens': ['they', "'re", 'right', 'behind', 'me', '.'],
#    'french_tokens': ['ils', 'sont', 'juste', 'derrière', 'moi', '.']},
#   {'english_tokens': ['they', "'re", 'right', 'behind', 'me', '.'],
#    'french_tokens': ['elles', 'sont', 'juste', 'derrière', 'moi', '.']},
#   {'english_tokens': ['they', "'re", 'self', 'sufficient', '.'],
#    'french_tokens': ['ils', 'sont', 'autosuffisants', '.']},
#   {'english_tokens': ['they', "'re", 'self', 'sufficient', '.'],
#    'french_tokens': ['elles', 'sont', 'autosuffisantes', '.']},
#   {'english_tokens': ['they', "'re", 'speaking', 'french', '.'],
#    'french_tokens': ['ils', 'parlent', 'en', 'français', '.']},
#   {'english_tokens': ['they', "'re", 'speaking', 'french', '.'],
#    'french_tokens': ['elles', 'parlent', 'en', 'français', '.']},
#   {'english_tokens': ['they', "'re", 'waiting', 'for', 'you', '.'],
#    'french_tokens': ['ils', "t'attendent", '.']},
#   {'english_tokens': ['they', "'re", 'waiting', 'for', 'you', '.'],
#    'french_tokens': ['elles', "t'attendent", '.']},
#   {'english_tokens': ['they', "'re", 'waiting', 'for', 'you', '.'],
#    'french_tokens': ['ils', 'vous', 'attendent', '.']},
#   {'english_tokens': ['they', "'re", 'waiting', 'for', 'you', '.'],
#    'french_tokens': ['elles', 'vous', 'attendent', '.']},
#   {'english_tokens': ['they', "'re", 'going', 'to', 'the', 'war', '.'],
#    'french_tokens': ['ils', 'vont', 'à', 'la', 'guerre', '.']},
#   {'english_tokens': ['they', "'re", 'going', 'to', 'the', 'war', '.'],
#    'french_tokens': ['elles', 'vont', 'à', 'la', 'guerre', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'always', 'right', '.'],
#    'french_tokens': ['ils', "n'ont", 'pas', 'toujours', 'raison', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'always', 'right', '.'],
#    'french_tokens': ['elles', "n'ont", 'pas', 'toujours', 'raison', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'following', 'me', '.'],
#    'french_tokens': ['ils', 'ne', 'me', 'suivent', 'pas', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'my', 'prisoners', '.'],
#    'french_tokens': ['ce', 'ne', 'sont', 'pas', 'mes', 'prisonniers', '.']},
#   {'english_tokens': ['they', "'re", 'playing', 'our', 'song', '.'],
#    'french_tokens': ['ils', 'jouent', 'notre', 'chanson', '.']},
#   {'english_tokens': ['they', "'re", 'playing', 'our', 'song', '.'],
#    'french_tokens': ['ils',
#     'sont',
#     'en',
#     'train',
#     'de',
#     'jouer',
#     'notre',
#     'chanson',
#     '.']},
#   {'english_tokens': ['they', "'re", 'right', 'behind', 'you', '.'],
#    'french_tokens': ['ils', 'sont', 'juste', 'derrière', 'vous', '.']},
#   {'english_tokens': ['they', "'re", 'right', 'behind', 'you', '.'],
#    'french_tokens': ['ils', 'sont', 'juste', 'derrière', 'toi', '.']},
#   {'english_tokens': ['they', "'re", 'right', 'behind', 'you', '.'],
#    'french_tokens': ['elles', 'sont', 'juste', 'derrière', 'vous', '.']},
#   {'english_tokens': ['they', "'re", 'right', 'behind', 'you', '.'],
#    'french_tokens': ['elles', 'sont', 'juste', 'derrière', 'toi', '.']},
#   {'english_tokens': ['they', "'re", 'right', 'behind', 'you', '.'],
#    'french_tokens': ['elles',
#     'se',
#     'trouvent',
#     'juste',
#     'derrière',
#     'vous',
#     '.']},
#   {'english_tokens': ['they', "'re", 'right', 'behind', 'you', '.'],
#    'french_tokens': ['elles',
#     'se',
#     'trouvent',
#     'juste',
#     'derrière',
#     'toi',
#     '.']},
#   {'english_tokens': ['they', "'re", 'right', 'behind', 'you', '.'],
#    'french_tokens': ['ils',
#     'se',
#     'trouvent',
#     'juste',
#     'derrière',
#     'vous',
#     '.']},
#   {'english_tokens': ['they', "'re", 'right', 'behind', 'you', '.'],
#    'french_tokens': ['ils',
#     'se',
#     'trouvent',
#     'juste',
#     'derrière',
#     'toi',
#     '.']},
#   {'english_tokens': ['they', "'re", 'right', ',', 'of', 'course', '.'],
#    'french_tokens': ['ils', 'ont', 'raison', ',', 'bien', 'sûr', '.']},
#   {'english_tokens': ['they', "'re", 'right', ',', 'of', 'course', '.'],
#    'french_tokens': ['elles', 'ont', 'raison', ',', 'bien', 'sûr', '.']},
#   {'english_tokens': ['they', "'re", 'terrified', 'of', 'you', '.'],
#    'french_tokens': ['vous', 'les', 'terrifiez', '.']},
#   {'english_tokens': ['they', "'re", 'terrified', 'of', 'you', '.'],
#    'french_tokens': ['tu', 'les', 'terrifies', '.']},
#   {'english_tokens': ['they', "'re", 'very', 'fond', 'of', 'him', '.'],
#    'french_tokens': ['elles', "l'adorent", '.']},
#   {'english_tokens': ['they', "'re", 'very', 'fond', 'of', 'him', '.'],
#    'french_tokens': ['ils', "l'adorent", '.']},
#   {'english_tokens': ['they', "'re", 'anxious', 'for', 'peace', '.'],
#    'french_tokens': ['ils', "s'inquiètent", 'pour', 'la', 'paix', '.']},
#   {'english_tokens': ['they', "'re", 'anxious', 'for', 'peace', '.'],
#    'french_tokens': ['elles', "s'inquiètent", 'pour', 'la', 'paix', '.']},
#   {'english_tokens': ['they', "'re", 'going', 'to', 'hang', 'tom', '.'],
#    'french_tokens': ['ils', 'vont', 'pendre', 'tom', '.']},
#   {'english_tokens': ['they', "'re", 'lucky', 'to', 'be', 'alive', '.'],
#    'french_tokens': ['ils', 'sont', 'chanceux', "d'être", 'en', 'vie', '.']},
#   {'english_tokens': ['they', "'re", 'lucky', 'to', 'be', 'alive', '.'],
#    'french_tokens': ['elles',
#     'ont',
#     'de',
#     'la',
#     'chance',
#     "d'être",
#     'vivantes',
#     '.']},
#   {'english_tokens': ['they', "'re", 'lucky', 'to', 'be', 'alive', '.'],
#    'french_tokens': ['elles',
#     'sont',
#     'chanceuses',
#     "d'être",
#     'en',
#     'vie',
#     '.']},
#   {'english_tokens': ['they', "'re", 'lucky', 'to', 'be', 'alive', '.'],
#    'french_tokens': ['ils',
#     'ont',
#     'de',
#     'la',
#     'chance',
#     "d'être",
#     'vivants',
#     '.']},
#   {'english_tokens': ['they', "'re", 'not', 'all', 'criminals', '.'],
#    'french_tokens': ['ce',
#     'ne',
#     'sont',
#     'pas',
#     'tous',
#     'des',
#     'criminels',
#     '.']},
#   {'english_tokens': ['they', "'re", 'of', 'no', 'consequence', '.'],
#    'french_tokens': ['ils', 'sont', 'sans', 'conséquence', '.']},
#   {'english_tokens': ['they', "'re", 'young', 'and', 'healthy', '.'],
#    'french_tokens': ['ils',
#     'sont',
#     'jeunes',
#     'et',
#     'en',
#     'bonne',
#     'santé',
#     '.']},
#   {'english_tokens': ['they', "'re", 'young', 'and', 'healthy', '.'],
#    'french_tokens': ['elles',
#     'sont',
#     'jeunes',
#     'et',
#     'en',
#     'bonne',
#     'santé',
#     '.']},
#   {'english_tokens': ['they', "'re", 'cleaning', 'the', 'beach', '.'],
#    'french_tokens': ['ils', 'nettoient', 'la', 'plage', '.']},
#   {'english_tokens': ['they', "'re", 'cleaning', 'the', 'beach', '.'],
#    'french_tokens': ['ils',
#     'sont',
#     'en',
#     'train',
#     'de',
#     'nettoyer',
#     'la',
#     'plage',
#     '.']},
#   {'english_tokens': ['they', "'re", 'in', 'the', 'science', 'lab', '.'],
#    'french_tokens': ['ils',
#     'sont',
#     'dans',
#     'le',
#     'laboratoire',
#     'de',
#     'sciences',
#     '.']},
#   {'english_tokens': ['they', "'re", 'in', 'the', 'science', 'lab', '.'],
#    'french_tokens': ['elles',
#     'sont',
#     'dans',
#     'le',
#     'laboratoire',
#     'de',
#     'sciences',
#     '.']},
#   {'english_tokens': ['they', "'re", 'out', 'of', 'their', 'minds', '.'],
#    'french_tokens': ['ils', 'ont', 'perdu', "l'esprit", '.']},
#   {'english_tokens': ['they', "'re", 'out', 'of', 'their', 'minds', '.'],
#    'french_tokens': ['elles', 'ont', 'perdu', "l'esprit", '.']},
#   {'english_tokens': ['they', "'re", 'probably', 'americans', '.'],
#    'french_tokens': ['ils', 'sont', 'probablement', 'étasuniens', '.']},
#   {'english_tokens': ['they', "'re", 'probably', 'americans', '.'],
#    'french_tokens': ['elles', 'sont', 'probablement', 'étasuniennes', '.']},
#   {'english_tokens': ['they', "'re", 'very', 'close', 'friends', '.'],
#    'french_tokens': ['ce', 'sont', 'des', 'amis', 'très', 'proches', '.']},
#   {'english_tokens': ['they', "'re", 'very', 'close', 'friends', '.'],
#    'french_tokens': ['ce', 'sont', 'des', 'amies', 'très', 'proches', '.']},
#   {'english_tokens': ['they', "'re", 'acting', 'on', 'their', 'own', '.'],
#    'french_tokens': ['ils', 'agissent', 'de', 'leur', 'propre', 'chef', '.']},
#   {'english_tokens': ['they', "'re", 'acting', 'on', 'their', 'own', '.'],
#    'french_tokens': ['elles',
#     'agissent',
#     'de',
#     'leur',
#     'propre',
#     'chef',
#     '.']},
#   {'english_tokens': ['they', "'re", 'enjoying', 'themselves', '.'],
#    'french_tokens': ['ils', "s'amusent", '.']},
#   {'english_tokens': ['they', "'re", 'enjoying', 'themselves', '.'],
#    'french_tokens': ['elles', "s'amusent", '.']},
#   {'english_tokens': ['they', "'re", 'part-time', 'employees', '.'],
#    'french_tokens': ['ce',
#     'sont',
#     'des',
#     'employés',
#     'à',
#     'temps',
#     'partiel',
#     '.']},
#   {'english_tokens': ['they', "'re", 'part-time', 'employees', '.'],
#    'french_tokens': ['ce',
#     'sont',
#     'des',
#     'employées',
#     'à',
#     'temps',
#     'partiel',
#     '.']},
#   {'english_tokens': ['they', "'re", 'thirty', 'dollars', 'each', '.'],
#    'french_tokens': ['ils', 'sont', 'à', 'trente', 'dollars', 'chacun', '.']},
#   {'english_tokens': ['they', "'re", 'thirty', 'dollars', 'each', '.'],
#    'french_tokens': ['elles',
#     'sont',
#     'à',
#     'trente',
#     'dollars',
#     'chacune',
#     '.']},
#   {'english_tokens': ['they', "'re", 'washing', 'their', 'hands', '.'],
#    'french_tokens': ['elles', 'se', 'lavent', 'les', 'mains', '.']},
#   {'english_tokens': ['they', "'re", 'against', 'animal', 'abuse', '.'],
#    'french_tokens': ['ils',
#     'militent',
#     'contre',
#     'les',
#     'violences',
#     'aux',
#     'animaux',
#     '.']},
#   {'english_tokens': ['they', "'re", 'dragging', 'their', 'heels', '.'],
#    'french_tokens': ['ils', 'traînent', 'les', 'pieds', '.']},
#   {'english_tokens': ['they', "'re", 'going', 'to', 'have', 'a', 'look', '.'],
#    'french_tokens': ['ils', 'vont', 'jeter', 'un', 'coup', "d'œil", '.']},
#   {'english_tokens': ['they', "'re", 'going', 'to', 'torture', 'tom', '.'],
#    'french_tokens': ['ils', 'vont', 'torturer', 'tom', '.']},
#   {'english_tokens': ['they', "'re", 'going', 'to', 'torture', 'tom', '.'],
#    'french_tokens': ['elles', 'vont', 'torturer', 'tom', '.']},
#   {'english_tokens': ['they', "'re", 'not', 'going', 'to', 'catch', 'us', '.'],
#    'french_tokens': ['ils', 'ne', 'vont', 'pas', 'nous', 'attraper', '.']},
#   {'english_tokens': ['they', "'re", 'related', 'to', 'each', 'other', '.'],
#    'french_tokens': ['ils', 'sont', 'apparentés', '.']},
#   {'english_tokens': ['they', "'re", 'smiling', 'at', 'each', 'other', '.'],
#    'french_tokens': ['ils', 'se', 'sourient', '.']},
#   {'english_tokens': ['they', "'re", 'smiling', 'at', 'each', 'other', '.'],
#    'french_tokens': ['elles', 'se', 'sourient', '.']},
#   {'english_tokens': ['they', "'re", 'the', 'cream', 'of', 'the', 'crop', '.'],
#    'french_tokens': ['ils', 'forment', 'le', 'dessus', 'du', 'panier', '.']},
#   {'english_tokens': ['they', "'re", 'the', 'cream', 'of', 'the', 'crop', '.'],
#    'french_tokens': ['elles', 'forment', 'le', 'dessus', 'du', 'panier', '.']},
#   {'english_tokens': ['they', "'re", 'walking', 'without', 'shoes', '.'],
#    'french_tokens': ['ils', 'marchent', 'pieds', 'nus', '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'eating',
#     'high',
#     'on',
#     'the',
#     'hog',
#     '.'],
#    'french_tokens': ['ils', 'mènent', 'grand', 'train', '.']},
#   {'english_tokens': ['they', "'re", 'going', 'to', 'make', 'mistakes', '.'],
#    'french_tokens': ['ils', 'vont', 'commettre', 'des', 'erreurs', '.']},
#   {'english_tokens': ['they', "'re", 'going', 'to', 'make', 'mistakes', '.'],
#    'french_tokens': ['elles', 'vont', 'commettre', 'des', 'erreurs', '.']},
#   {'english_tokens': ['they', "'re", 'keeping', 'it', 'under', 'wraps', '.'],
#    'french_tokens': ['ils', 'le', 'tiennent', 'secret', '.']},
#   {'english_tokens': ['they', "'re", 'keeping', 'it', 'under', 'wraps', '.'],
#    'french_tokens': ['ils', 'le', 'gardent', 'secret', '.']},
#   {'english_tokens': ['they', "'re", 'suffering', 'from', 'malaria', '.'],
#    'french_tokens': ['ils', 'souffrent', 'du', 'paludisme', '.']},
#   {'english_tokens': ['they', "'re", 'looking', 'for', 'a', 'scapegoat', '.'],
#    'french_tokens': ['ils', 'cherchent', 'un', 'bouc', 'émissaire', '.']},
#   {'english_tokens': ['they', "'re", 'looking', 'for', 'a', 'scapegoat', '.'],
#    'french_tokens': ['elles', 'cherchent', 'un', 'bouc', 'émissaire', '.']},
#   {'english_tokens': ['they', "'re", 'barely', 'paid', 'minimum', 'wage', '.'],
#    'french_tokens': ['ils', 'sont', 'à', 'peine', 'payés', 'le', 'smic', '.']},
#   {'english_tokens': ['they', "'re", 'giving', 'away', 'samples', 'free', '.'],
#    'french_tokens': ['ils',
#     'distribuent',
#     'des',
#     'échantillons',
#     'gratuits',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'not',
#     'telling',
#     'us',
#     'the',
#     'truth',
#     '.'],
#    'french_tokens': ['ils',
#     'ne',
#     'nous',
#     'disent',
#     'pas',
#     'la',
#     'vérité',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'living',
#     'in',
#     'a',
#     'fantasy',
#     'world',
#     '.'],
#    'french_tokens': ['elles',
#     'vivent',
#     'dans',
#     'un',
#     'monde',
#     'de',
#     'fantaisie',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'two',
#     'very',
#     'different',
#     'things',
#     '.'],
#    'french_tokens': ['ce',
#     'sont',
#     'deux',
#     'choses',
#     'absolument',
#     'différentes',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'back',
#     'where',
#     'they',
#     'want',
#     'to',
#     'be',
#     '.'],
#    'french_tokens': ['ils',
#     'sont',
#     'de',
#     'retour',
#     'là',
#     'où',
#     'ils',
#     'veulent',
#     'être',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'back',
#     'where',
#     'they',
#     'want',
#     'to',
#     'be',
#     '.'],
#    'french_tokens': ['elles',
#     'sont',
#     'de',
#     'retour',
#     'là',
#     'où',
#     'elles',
#     'veulent',
#     'être',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'sunbathing',
#     'around',
#     'the',
#     'pool',
#     '.'],
#    'french_tokens': ['ils', 'bronzent', 'autour', 'de', 'la', 'piscine', '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'sunbathing',
#     'around',
#     'the',
#     'pool',
#     '.'],
#    'french_tokens': ['elles',
#     'bronzent',
#     'autour',
#     'de',
#     'la',
#     'piscine',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'going',
#     'to',
#     'give',
#     'me',
#     'an',
#     'estimate',
#     '.'],
#    'french_tokens': ['ils', 'vont', 'me', 'donner', 'un', 'devis', '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'having',
#     'a',
#     'break',
#     'at',
#     'the',
#     'moment',
#     '.'],
#    'french_tokens': ['pour',
#     'le',
#     'moment',
#     ',',
#     'ils',
#     'font',
#     'une',
#     'pause',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'really',
#     'good',
#     'at',
#     'making',
#     'clothes',
#     '.'],
#    'french_tokens': ['ils',
#     'sont',
#     'vraiment',
#     'bons',
#     'dans',
#     'la',
#     'confection',
#     'de',
#     'vêtements',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'both',
#     'in',
#     'love',
#     'with',
#     'the',
#     'same',
#     'guy',
#     '.'],
#    'french_tokens': ['elles',
#     'sont',
#     'toutes',
#     'les',
#     'deux',
#     'amoureuses',
#     'du',
#     'même',
#     'type',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'both',
#     'in',
#     'love',
#     'with',
#     'the',
#     'same',
#     'guy',
#     '.'],
#    'french_tokens': ['elles',
#     'sont',
#     'toutes',
#     'deux',
#     'amoureuses',
#     'du',
#     'même',
#     'type',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'here',
#     'until',
#     'the',
#     'end',
#     'of',
#     'the',
#     'week',
#     '.'],
#    'french_tokens': ['ils',
#     'sont',
#     'là',
#     'jusqu',
#     "'",
#     'à',
#     'la',
#     'fin',
#     'de',
#     'la',
#     'semaine',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'studying',
#     'french',
#     'and',
#     'web',
#     'design',
#     '.'],
#    'french_tokens': ['ils',
#     'étudient',
#     'le',
#     'français',
#     'et',
#     'le',
#     'webdesign',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'both',
#     'in',
#     'love',
#     'with',
#     'the',
#     'same',
#     'girl',
#     '.'],
#    'french_tokens': ['ils',
#     'sont',
#     'tous',
#     'les',
#     'deux',
#     'amoureux',
#     'de',
#     'la',
#     'même',
#     'fille',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'both',
#     'in',
#     'love',
#     'with',
#     'the',
#     'same',
#     'girl',
#     '.'],
#    'french_tokens': ['ils',
#     'sont',
#     'tous',
#     'deux',
#     'amoureux',
#     'de',
#     'la',
#     'même',
#     'fille',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'going',
#     'to',
#     'have',
#     'a',
#     'party',
#     'next',
#     'week',
#     '.'],
#    'french_tokens': ['ils',
#     'vont',
#     'faire',
#     'une',
#     'fête',
#     'la',
#     'semaine',
#     'prochaine',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'expressing',
#     'their',
#     'love',
#     'by',
#     'hugging',
#     '.'],
#    'french_tokens': ['ils',
#     'expriment',
#     'leur',
#     'amour',
#     'en',
#     "s'enlaçant",
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'taking',
#     'mary',
#     'to',
#     'the',
#     'emergency',
#     'room',
#     '.'],
#    'french_tokens': ['ils',
#     'emmènent',
#     'marie',
#     'à',
#     'la',
#     'salle',
#     'des',
#     'urgences',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'bringing',
#     'him',
#     'in',
#     'for',
#     'questioning',
#     'now',
#     '.'],
#    'french_tokens': ['ils',
#     'sont',
#     'actuellement',
#     'en',
#     'train',
#     'de',
#     "l'amener",
#     'pour',
#     'lui',
#     'poser',
#     'des',
#     'questions',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'having',
#     'a',
#     'going-out-of-business',
#     'sale',
#     '.'],
#    'french_tokens': ['ils', 'ont', 'une', 'liquidation', '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'constructing',
#     'a',
#     'bridge',
#     'over',
#     'the',
#     'river',
#     '.'],
#    'french_tokens': ['ils',
#     'construisent',
#     'un',
#     'pont',
#     'au-dessus',
#     'de',
#     'la',
#     'rivière',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'eating',
#     'dinner',
#     'now',
#     'in',
#     'the',
#     'dining',
#     'room',
#     '.'],
#    'french_tokens': ['ils',
#     'déjeunent',
#     'maintenant',
#     'dans',
#     'la',
#     'salle-à-manger',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'eating',
#     'dinner',
#     'now',
#     'in',
#     'the',
#     'dining',
#     'room',
#     '.'],
#    'french_tokens': ['elles',
#     'déjeunent',
#     'maintenant',
#     'dans',
#     'la',
#     'salle-à-manger',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'eating',
#     'dinner',
#     'now',
#     'in',
#     'the',
#     'dining',
#     'room',
#     '.'],
#    'french_tokens': ['ils',
#     'dînent',
#     'maintenant',
#     'dans',
#     'la',
#     'salle-à-manger',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'eating',
#     'dinner',
#     'now',
#     'in',
#     'the',
#     'dining',
#     'room',
#     '.'],
#    'french_tokens': ['elles',
#     'dînent',
#     'maintenant',
#     'dans',
#     'la',
#     'salle-à-manger',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'just',
#     'like',
#     'rats',
#     'leaving',
#     'a',
#     'sinking',
#     'ship',
#     '.'],
#    'french_tokens': ['ils',
#     'sont',
#     'juste',
#     'comme',
#     'des',
#     'rats',
#     'quittant',
#     'un',
#     'navire',
#     'qui',
#     'sombre',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'not',
#     'going',
#     'to',
#     'be',
#     'able',
#     'to',
#     'find',
#     'the',
#     'hotel',
#     '.'],
#    'french_tokens': ['ils',
#     'ne',
#     'vont',
#     'pas',
#     'pouvoir',
#     'trouver',
#     "l'hôtel",
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'hoping',
#     'the',
#     'wheat',
#     'harvest',
#     'will',
#     'be',
#     'good',
#     'this',
#     'year',
#     '.'],
#    'french_tokens': ['ils',
#     'espèrent',
#     'que',
#     'la',
#     'récolte',
#     'de',
#     'blé',
#     'sera',
#     'bonne',
#     'cette',
#     'année',
#     '.']},
#   {'english_tokens': ['they',
#     "'re",
#     'experiencing',
#     'white',
#     'water',
#     'rafting',
#     'on',
#     'a',
#     'class',
#     'five',
#     'river',
#     '.'],
#    'french_tokens': ['ils',
#     'font',
#     "l'expérience",
#     'du',
#     'radeau',
#     'en',
#     'eau',
#     'vive',
#     ',',
#     'sur',
#     'une',
#     'rivière',
#     'de',
#     'classe',
#     'cinq',
#     '.']}])
# ```
# %%
counts = {k: len(v) for k, v in data_subset.items()}
counts, sum(counts.values())

# %%
np.random.seed(args.seed)

dataset_stage3 = []
for phrase, datum_list in sorted(data_subset.items()):
    np.random.shuffle(datum_list)
    n_train = int(len(datum_list) * args.perc_train)
    n_val = int(len(datum_list) * args.perc_val)

    for datum in datum_list[:n_train]:
        datum["split"] = "train"

    for datum in datum_list[n_train : n_train + n_val]:
        datum["split"] = "val"

    for datum in datum_list[n_train + n_val :]:
        datum["split"] = "test"

    dataset_stage3.extend(datum_list)

# %%
# here we pop and assign into the dictionary, thus modifying in place
for datum in dataset_stage3:
    datum["source_language"] = " ".join(datum.pop("english_tokens"))
    datum["target_language"] = " ".join(datum.pop("french_tokens"))

# %%
nmt_df = pd.DataFrame(dataset_stage3)

# %%
nmt_df.head()

# %%
nmt_df.to_csv(args.output_data_path)
